[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sfts"
version = "0.1.0"
description = "Secure File Transfer System"
requires-python = ">=3.10"
